version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
    # Ignore patch updates for some packages
    - dependency-name: "com.android.tools.build*"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "kotlin_version"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "kotlin"
      update-types: ["version-update:semver-patch"]
    - dependency-name: "com.google.firebase*"
      update-types: ["version-update:semver-patch"]
