# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  batch: true
  branches:
    include:
      - refs/tags/*

variables:
- name: wrapperScript
  value: 'gradlew' # 'gradlew.bat' is for a Windows environment, use 'gradlew' for UNIX e.g. Ubuntu/MacOS
- name: PACKAGING_URL
  value: 'https://pkgs.dev.azure.com/tingle/_packaging/tingle-maven/maven/v1'
- name: PACKAGING_USERNAME
  value: 'AZURE_ARTIFACTS'


stages: 
#################################################################################
#       Build with Gradle
#################################################################################
- stage: Build
    
  jobs:
    - job: Build

      pool:
        vmImage: 'ubuntu-latest'
        demands:
          - java
          - JDK

      steps:
        - task: gitversion/setup@0
          inputs:
            versionSpec: '5.x'

        - task: gitversion/execute@0
          inputs:
            useConfigFile: true
            configFilePath: '$(Build.SourcesDirectory)/GitVersion.yml'

        # TODO: add tasks for build and test before assembling

        - task: Gradle@2
          displayName: 'gradlew assembleRelease'
          inputs:
            gradleWrapperFile: '$(wrapperScript)'
            tasks: 'assembleRelease'
            testResultsFiles: '**/build/test-results/TEST-*.xml'

        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
          inputs:
            sourceFolder: '$(build.sourcesdirectory)'
            contents: '**/*.aar'
            targetFolder: '$(build.artifactstagingdirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'
          inputs:
            pathtoPublish: '$(build.artifactstagingdirectory)'

#################################################################################
#       Publish to maven
#################################################################################
- stage: Publish
  dependsOn: Build
  # only publish to maven from a tag
  condition: |
      and
      (
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )

  jobs:  
    - job: Publish    

      pool:
        vmImage: 'ubuntu-latest'
        
      steps:
      - task: Gradle@1
        displayName: 'gradlew publish --stacktrace'
        inputs:
            gradleWrapperFile: '$(wrapperScript)'
            tasks: 'publish --stacktrace'
            publishJUnitResults: false