name: Build and Publish

on:
  push:
    tags:
      - '*'
    paths-ignore: # do not trigger for changes:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish To maven central
        run: ./gradlew publish --max-workers 1 closeAndReleaseStagingRepository --stacktrace
        env:
          PUBLISHING_PROFILE_ID: ${{ secrets.PUBLISHING_PROFILE_ID }}
          PUBLISHING_USERNAME: ${{ secrets.PUBLISHING_USERNAME }}
          PUBLISHING_PASSWORD: ${{ secrets.PUBLISHING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          VERSION_NAME: ${{ steps.gitversion.outputs.semVer }}